name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: ['black', 'bandit', 'pylint', 'flake8']
        include:
          - tools: pytest
            args: -m not integration and not gpu
          - tools: pytest
            args: -m integration

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ${{ matrix.tools }} validation
        run: |
          if [ "${{ matrix.tools }}" == "black" ]; then
            black --check .
          elif [ "${{ matrix.tools }}" == "bandit" ]; then
            bandit -r .
          elif [ "${{ matrix.tools }}" == "pylint" ]; then
            pylint --rcfile=setup.cfg --fail-under=9.0 --reports=n --score=n --output-format=colorized .
          elif [ "${{ matrix.tools }}" == "flake8" ]; then
            flake8 --config=setup.cfg .
          elif [ "${{ matrix.tools }}" == "pytest" ]; then
            pytest ${{ matrix.args }}
          fi
