name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: ['black', 'bandit', 'pylint', 'flake8']
        include:
          - tools: pytest
            args: -m not integration and not gpu
          - tools: pytest
            args: -m integration